### ISSUE TITLE
Invocation via npx doesn't work

### ISSUE THREAD

**Issue by cbrunnkvist** [EasyGraphQL/easygraphql-lt#4]
Running `npx easygraphql-lt my-conf.json`

Expected:
- it to work?

Actual:
```
Error: internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'graphql'
```

Perhaps I'm missing something basic, but the README doesn't seem to give me any further hints.

**Comment by estrada9166** [comment]
It should work now with the fix on #5
