### ISSUE TITLE
Description of how to run when not using server

### ISSUE THREAD

**Issue by julielaursenKW** [EasyGraphQL/easygraphql-lt#6]
Hi, sorry to bother but I'd love to use this tool. I am not QA and I don't have a local server on my machine and honestly, if I put a local server on my machine I'm not sure I'd be testing the right environment. I have the graphql url and the schema/docs available to me. I'm on windows10 with npm version 6.13.2 and node v12.13.1. I tried just installing the project with npm install easygraphql-lt and that worked, and then I just created a load test file with nothing more than:

"url": "http://test.loadimpact.com"
"name": "testing a public site"

in it. But when I run the npx command I get :

$ npx easygrapql-lt script.json
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/easygrapql-lt - Not found
npm ERR! 404
npm ERR! 404  'easygrapql-lt@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

I'm not a developer, and I'm really not sure what to do from here :(

**Comment by estrada9166** [comment]
Closing this one! it should be working fine with `npx` if persisted we can re-open
