### ISSUE TITLE
Error: The system cannot find the path specified.

### ISSUE THREAD

**Issue by astavria4** [EasyGraphQL/easygraphql-lt#9]
{
    "config":{
        "url": "http://localhost:8080/v1/graphql",
        "name": "testing",
        "queryFile": true,
        "duration": 5,
        "arrivalRate": 10
    },
    "args":{
        "mission":{
          "id": "1"
        }
      }
}

I have 1 folder named with-dataLoaders that has the lt.json as in your youtube video. 

When I run the following command,
C:\Training\testing\with-dataLoaders>npx easygraphql-lt lt.json

I get  - Error: The system cannot find the path specified.

Is there something I am missing?

**Comment by estrada9166** [comment]
I don't see anything missing there - are running `npx` in the root of `with-dataLoaders`?

**Comment by astavria4** [comment]
Hi @estrada9166, sorry for the late response. I have actually started to implement the easygrapqhl-load-tester instead of this project. I will close this incident. I do have another incident / question for easygraphql-load-tester. My company and I are going to be using the easygraphql suite  for our graphql testing. Is there anyway we can open a line of communication between us and you and your team?
